server:
  port: 9001

spring:
  application:
    name: mscv-pacientes
  jpa:
      hibernate.ddl-auto: create-drop
      generate-ddl: true
      show-sql: true
      database-platform: org.hibernate.dialect.MySQL8Dialect
  datasource:
    url: jdbc:mysql://localhost:3306/paciente
    username: root
    password: Isabella2013*


